bash scripts/retrieve_from_hf.sh cos_e v1.11
bash scripts/retrieve_from_hf.sh cosmos_qa None
bash scripts/retrieve_from_hf.sh dream None
bash scripts/retrieve_from_hf.sh openbookqa main
bash scripts/retrieve_from_hf.sh super_glue boolq
bash scripts/retrieve_from_hf.sh super_glue multirc
bash scripts/retrieve_from_hf.sh piqa None
bash scripts/retrieve_from_hf.sh qasc None
bash scripts/retrieve_from_hf.sh quail None
bash scripts/retrieve_from_hf.sh quarel None
bash scripts/retrieve_from_hf.sh quartz None
bash scripts/retrieve_from_hf.sh race high
bash scripts/retrieve_from_hf.sh race middle
bash scripts/retrieve_from_hf.sh sciq None 
bash scripts/retrieve_from_hf.sh social_i_qa None 
bash scripts/retrieve_from_hf.sh wiki_hop original 
bash scripts/retrieve_from_hf.sh wiqa None 